-- Oracle schema: minimal tables and sequences to start
CREATE TABLE roles (
  role_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role_name VARCHAR2(50) NOT NULL UNIQUE
);

CREATE TABLE users (
  user_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR2(100) UNIQUE NOT NULL,
  password_hash VARCHAR2(512) NOT NULL,
  salt VARCHAR2(256) NOT NULL,
  role_id NUMBER NOT NULL,
  is_locked CHAR(1) DEFAULT 'N' CHECK (is_locked IN ('Y','N')),
  failed_attempts NUMBER DEFAULT 0,
  last_login TIMESTAMP,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE patients (
  patient_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR2(200) NOT NULL,
  last_name VARCHAR2(200) NOT NULL,
  national_id VARCHAR2(50),
  phone VARCHAR2(50),
  email VARCHAR2(200),
  birth_date DATE,
  blood_type VARCHAR2(10),
  allergies CLOB,
  chronic_conditions CLOB,
  address CLOB,
  is_deleted CHAR(1) DEFAULT 'N' CHECK (is_deleted IN ('Y','N')),
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  updated_at TIMESTAMP
);

CREATE TABLE consultations (
  consult_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  patient_id NUMBER NOT NULL,
  doctor_id NUMBER,
  status VARCHAR2(20) DEFAULT 'Draft',
  symptoms CLOB,
  diagnosis CLOB,
  prescription CLOB,
  notes CLOB,
  created_at TIMESTAMP DEFAULT SYSTIMESTAMP,
  validated_at TIMESTAMP,
  archived_at TIMESTAMP,
  is_deleted CHAR(1) DEFAULT 'N' CHECK (is_deleted IN ('Y','N'))
);

CREATE TABLE audit_log (
  audit_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  event_time TIMESTAMP DEFAULT SYSTIMESTAMP,
  user_id NUMBER,
  username VARCHAR2(100),
  action VARCHAR2(200),
  object_type VARCHAR2(100),
  object_id VARCHAR2(100),
  details CLOB,
  immutable_flag CHAR(1) DEFAULT 'Y' CHECK (immutable_flag IN ('Y','N'))
);

-- Minimal indexes for search
CREATE INDEX idx_patients_name ON patients (UPPER(last_name));
CREATE INDEX idx_patients_nid ON patients (national_id);

-- Seed roles
INSERT INTO roles (role_name) VALUES ('Admin');
INSERT INTO roles (role_name) VALUES ('Doctor');
INSERT INTO roles (role_name) VALUES ('Nurse');
INSERT INTO roles (role_name) VALUES ('Receptionist');

COMMIT;
